#!/usr/bin/env python3
"""Generador del curso de Base de Datos - 20 niveles con UI Python-style"""
import os, json

OUT = r"C:\Users\MINEDUCYT\OneDrive\Documentos\verdadera-academia\database_course.html"

# Read existing gen_db_full.py for HTML head
with open(r"C:\Users\MINEDUCYT\OneDrive\Documentos\verdadera-academia\_tools\gen_db_full.py", "r", encoding="utf-8") as f:
    gen = f.read()

# Extract parts
s1 = gen.find('HTML_HEAD = """') + len('HTML_HEAD = """')
e1 = gen.find('"""', s1)
html_head = gen[s1:e1]

print(f"HTML_HEAD: {len(html_head)} chars")

# Build the complete file
lines = []
lines.append(html_head)
lines.append('<script>')
lines.append('const COURSE_ID = "database";')
lines.append('let currentLevel = 0, currentLessonStep = 0, currentQuizQuestion = 0, score = 0, resultsScoreV = 0;')
lines.append('let userProgress = { completedLevels: [], quizScores: {} };')
lines.append('')
lines.append('document.addEventListener("DOMContentLoaded", async () => {')
lines.append('    const s = JSON.parse(localStorage.getItem("currentUser"));')
lines.append('    if (!s || !s.id) { window.location.href = "menu_inicio.html"; return; }')
lines.append('    const sp = localStorage.getItem("databaseCourseProgress");')
lines.append('    if (sp) { try { userProgress = JSON.parse(sp); } catch(e) { userProgress = { completedLevels: [], quizScores: {} }; } }')
lines.append('    if (!userProgress.completedLevels) userProgress.completedLevels = [];')
lines.append('    if (!userProgress.quizScores) userProgress.quizScores = {};')
lines.append('    renderLevelSelection(); showPanel("levelSelection");')
lines.append('    if (window.lucide) lucide.createIcons();')
lines.append('});')
lines.append('')
lines.append('function saveProgress() {')
lines.append('    const u = JSON.parse(localStorage.getItem("currentUser") || "{}");')
lines.append('    const p = { ...userProgress, lastUpdated: new Date().toISOString() };')
lines.append('    if (u.id && window.updateCourseProgress) {')
lines.append('        u.databaseProgress = p; localStorage.setItem("currentUser", JSON.stringify(u));')
lines.append('        try { window.updateCourseProgress(u.id, "databaseProgress", p); } catch(e) {}')
lines.append('    }')
lines.append('    localStorage.setItem("databaseCourseProgress", JSON.stringify(userProgress));')
lines.append('}')
lines.append('')
lines.append('function markLevelCompleted(i) {')
lines.append('    if (!userProgress.completedLevels.includes(i)) { userProgress.completedLevels.push(i); saveProgress(); showLevelUpNotification(); }')
lines.append('    renderLevelSelection();')
lines.append('}')
lines.append('function showLevelUpNotification() {')
lines.append('    const n = document.createElement("div"); n.className = "fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-50";')
lines.append('    n.innerHTML = \'<div class="bg-green-600 text-white px-6 py-4 rounded-lg shadow-xl text-center animate-bounce"><div class="text-4xl mb-2">🎉</div><div class="text-xl font-bold">¡Nivel Completado!</div></div>\';')
lines.append('    document.body.appendChild(n); setTimeout(() => { if (n.parentNode) n.parentNode.removeChild(n); }, 3000);')
lines.append('}')
lines.append('')
lines.append('const panels = { levelSelection: document.getElementById("level-selection-panel"), lesson: document.getElementById("lesson-panel"), quiz: document.getElementById("quiz-panel"), results: document.getElementById("results-panel") };')
lines.append('function showPanel(n) { Object.values(panels).forEach(p => { if(p) p.classList.remove("active"); }); if(panels[n]) panels[n].classList.add("active"); if (window.lucide) lucide.createIcons(); }')
lines.append('')
lines.append('function renderLevelSelection() {')
lines.append('    const g = document.getElementById("level-grid"); if (!g) return; g.innerHTML = "";')
lines.append('    g.style.cssText = "display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: 0.9rem; width: 100%; max-width: 860px; margin-bottom: 2rem;";')
lines.append('    const t = courseData.length, c = userProgress.completedLevels.length, pct = Math.round((c/t)*100);')
lines.append('    const pb = document.getElementById("overall-progress-bar"), pt = document.getElementById("overall-progress-text");')
lines.append('    if (pb) pb.style.width = pct + "%"; if (pt) pt.textContent = c+"/"+t+" niveles";')
lines.append('    courseData.forEach((lv, i) => {')
lines.append('        const u = i===0 || userProgress.completedLevels.includes(i-1), done = userProgress.completedLevels.includes(i);')
lines.append('        const nd = document.createElement("div"); nd.className = "level-node "+(u?"unlocked":"locked")+(done?" completed":"");')
lines.append('        if (done) { const rb = document.createElement("div"); rb.className="status-ribbon"; rb.innerText="HECHO"; nd.appendChild(rb); }')
lines.append('        const ic = document.createElement("div"); ic.className="node-icon"; ic.innerHTML=\'<i data-lucide="\'+(done?"check-circle":u?"play-circle":"lock")+\'"></i>\'; nd.appendChild(ic);')
lines.append('        const inf = document.createElement("div"); inf.className="flex flex-col items-center gap-1"; inf.innerHTML=\'<span class="node-number">Nivel \'+(i+1)+\'</span><div class="node-title">\'+lv.title+\'</div>\'; nd.appendChild(inf);')
lines.append('        if (u) nd.onclick = () => startLevel(i); g.appendChild(nd);')
lines.append('    });')
lines.append('    if (window.lucide) lucide.createIcons();')
lines.append('}')
lines.append('')
lines.append('function startLevel(i) { currentLevel=i; currentLessonStep=0; showPanel("lesson"); setTimeout(()=>renderLesson(),50); }')
lines.append('let lessonMainMonacoEditor=null, originalLessonHTML="", monacoRequireConfigured=false;')
lines.append('function ensureMonacoLoaded(cb) { if(window.monaco) return cb(); if(!monacoRequireConfigured){ require.config({paths:{"vs":"https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.36.1/min/vs"}}); monacoRequireConfigured=true; } require(["vs/editor/editor.main"],()=>{ window.monaco=monaco; if(window.themeManager) window.themeManager.defineCustomThemes(); cb(); }); }')
lines.append('function restoreLessonContent() { if(originalLessonHTML!==""){ const c=document.getElementById("lesson-content"); c.style.opacity="0"; setTimeout(()=>{ c.innerHTML=originalLessonHTML; c.style.opacity="1"; originalLessonHTML=""; document.getElementById("lesson-narrator-title").textContent="Teoria y Conceptos"; document.getElementById("lesson-narrator-subtitle").textContent="Lectura"; document.getElementById("lesson-narrator-icon").innerHTML=\'<i data-lucide="book-open" class="w-4 h-4"></i>\'; if(window.lucide) lucide.createIcons(); },200); } }')
lines.append('function startLessonTour(steps) { if(!steps||!steps.length) return; const c=document.getElementById("lesson-content"); if(originalLessonHTML==="") originalLessonHTML=c.innerHTML; let cur=0; document.getElementById("lesson-narrator-title").textContent="Guia Interactiva"; document.getElementById("lesson-narrator-subtitle").textContent="Anatomia del codigo"; document.getElementById("lesson-narrator-icon").innerHTML=\'<i data-lucide="microscope" class="w-4 h-4"></i>\'; function render(idx) { if(idx>=steps.length){ restoreLessonContent(); return; } const s=steps[idx]; if(lessonMainMonacoEditor&&s.line){ const d=[{range:new monaco.Range(s.line,1,s.line,1),options:{isWholeLine:true,className:"bg-accent/40 border-l-4 border-accent"}}]; if(!window.tourDecorations) window.tourDecorations=lessonMainMonacoEditor.createDecorationsCollection(); window.tourDecorations.set(d); lessonMainMonacoEditor.revealLineInCenter(s.line); } const bt=idx===steps.length-1?"Completar Analisis":"Siguiente Linea", bn=idx===steps.length-1?"check-circle":"arrow-down-circle"; c.style.opacity="0"; setTimeout(()=>{ c.innerHTML=\'<div class="mb-4 flex flex-wrap gap-3 justify-between items-center"><button id="tour-back-btn" class="btn-secondary flex items-center gap-2 px-4 py-2 text-sm bg-accent/20 border-accent/40 hover:bg-accent/40 text-accent transition"><i data-lucide="arrow-left" class="w-4 h-4"></i> Regresar</button><span class="text-sm font-mono text-gray-400 bg-black/40 px-3 py-1 rounded-full border border-white/5">Paso \'+(idx+1)+\' de \'+steps.length+\'</span></div><div class="glass p-6 rounded-xl border border-accent/30 bg-black/20 shadow-xl relative mt-4"><div class="flex items-center gap-3 mb-4 border-b border-white/10 pb-3"><div class="w-10 h-10 rounded-full bg-accent/20 flex flex-shrink-0 items-center justify-center text-accent"><i data-lucide="focus" class="w-5 h-5"></i></div><h3 class="text-lg font-bold text-white">\'+(s.title||"Linea "+s.line)+\'</h3></div><div class="prose prose-invert text-gray-200 mb-6">\'+s.text+\'</div><div class="flex justify-end pt-4"><button id="tour-next-btn" class="btn-primary flex items-center gap-2">\'+bt+\' <i data-lucide="\'+bn+\'" class="w-4 h-4"></i></button></div></div>\'; c.style.opacity="1"; if(window.lucide) lucide.createIcons(); document.getElementById("tour-back-btn").onclick=restoreLessonContent; document.getElementById("tour-next-btn").onclick=()=>render(idx+1); },150); } render(cur); }')
lines.append('')
lines.append('function renderLesson() {')
lines.append('    if(lessonMainMonacoEditor){ lessonMainMonacoEditor.dispose(); lessonMainMonacoEditor=null; }')
lines.append('    const lv=courseData[currentLevel], st=lv.lesson[currentLessonStep];')
lines.append('    document.getElementById("lesson-title").textContent="Nivel "+(currentLevel+1)+": "+(st.title||"Leccion");')
lines.append('    const dp=document.getElementById("lesson-dialog-panel"), cp=document.getElementById("lesson-code-panel"), lc=document.getElementById("lesson-content");')
lines.append('    dp.style.opacity="0"; dp.style.transform="translateY(10px)";')
lines.append('    setTimeout(()=>{')
lines.append('        if(st.dialogo){')
lines.append('            lc.innerHTML=st.dialogo;')
lines.append('            if(st.codigo){')
lines.append('                cp.classList.remove("hidden"); cp.classList.add("flex"); dp.classList.replace("lg:w-full","lg:w-1/2");')
lines.append('                document.getElementById("lesson-code-filename").textContent=st.filename||"ejemplo.sql";')
lines.append('                const tb=document.getElementById("code-tour-btn");')
lines.append('                if(tb){ if(st.tourSteps&&st.tourSteps.length>0){ tb.classList.add("visible"); tb.onclick=()=>startLessonTour(st.tourSteps); } else { tb.classList.remove("visible"); tb.onclick=null; } }')
lines.append('                setTimeout(()=>{ const ct=document.getElementById("lesson-monaco-container"); if(ct){ ensureMonacoLoaded(()=>{ lessonMainMonacoEditor=window.monaco.editor.create(ct,{value:st.codigo.trim(),language:"sql",theme:"tokyo-night",readOnly:true,minimap:{enabled:false},fontSize:14,fontFamily:"\'JetBrains Mono\', monospace",scrollBeyondLastLine:false,padding:{top:16},automaticLayout:true}); if(st.tourSteps&&st.tourSteps.length>0) setTimeout(()=>startLessonTour(st.tourSteps),300); }); } },100);')
lines.append('            } else { cp.classList.add("hidden"); cp.classList.remove("flex"); dp.classList.replace("lg:w-1/2","lg:w-full"); }')
lines.append('        } else if(st.content){ cp.classList.add("hidden"); cp.classList.remove("flex"); dp.classList.replace("lg:w-1/2","lg:w-full"); lc.innerHTML=st.content; }')
lines.append('        dp.style.opacity="1"; dp.style.transform="translateY(0)";')
lines.append('    },150);')
lines.append('    document.getElementById("lesson-step").textContent=(currentLessonStep+1)+" / "+lv.lesson.length;')
lines.append('    document.getElementById("lesson-progress").style.width=((currentLessonStep+1)/lv.lesson.length*100)+"%";')
lines.append('    document.getElementById("prev-btn").disabled=currentLessonStep===0;')
lines.append('    const nb=document.getElementById("next-btn");')
lines.append('    if(currentLessonStep===lv.lesson.length-1) nb.innerHTML=\'Iniciar Quiz <i data-lucide="zap" class="w-4 h-4 ml-2"></i>\';')
lines.append('    else nb.innerHTML=\'Siguiente <i data-lucide="arrow-right" class="w-4 h-4 ml-2"></i>\';')
lines.append('    setTimeout(()=>{ if(window.lucide) lucide.createIcons(); },200);')
lines.append('}')
lines.append('')
lines.append('let currentQuizData={};')
lines.append('function startQuiz(){ currentQuizQuestion=0; score=0; renderQuizQuestion(); showPanel("quiz"); }')
lines.append('function renderQuizQuestion(){')
lines.append('    const lv=courseData[currentLevel], qd=lv.quiz[currentQuizQuestion]; currentQuizData=qd;')
lines.append('    document.getElementById("quiz-level-title").textContent="Quiz - Nivel "+(currentLevel+1);')
lines.append('    document.getElementById("quiz-progress").textContent=(currentQuizQuestion+1)+"/"+lv.quiz.length;')
lines.append('    document.getElementById("quiz-question").textContent=qd.question;')
lines.append('    document.getElementById("quiz-type-indicator").textContent="Seleccion multiple";')
lines.append('    document.querySelectorAll("#quiz-content > div").forEach(c=>c.classList.add("hidden"));')
lines.append('    document.getElementById("quiz-feedback").classList.add("hidden");')
lines.append('    renderMultipleChoice();')
lines.append('    document.getElementById("quiz-hint-btn").onclick=()=>alert("Lee todas las opciones cuidadosamente.");')
lines.append('}')
lines.append('function renderMultipleChoice(){')
lines.append('    const ct=document.getElementById("multiple-choice-container"); ct.classList.remove("hidden"); ct.innerHTML="";')
lines.append('    const shuffled=[...currentQuizData.options].sort(()=>Math.random()-0.5);')
lines.append('    const lm=["a","b","c","d","e","f","g","h"];')
lines.append('    shuffled.forEach((opt,i)=>{')
lines.append('        const b=document.createElement("button"); b.className="quiz-option p-4 rounded-lg text-left";')
lines.append('        b.innerHTML=\'<span class="option-letter">\'+lm[i]+\'</span><span>\'+opt+\'</span>\';')
lines.append('        b.onclick=()=>{ if(opt===currentQuizData.answer) score++; currentQuizQuestion++; if(currentQuizQuestion<courseData[currentLevel].quiz.length) renderQuizQuestion(); else showResults(); };')
lines.append('        ct.appendChild(b);')
lines.append('    });')
lines.append('}')
lines.append('function showResults(){')
lines.append('    const tq=courseData[currentLevel].quiz.length, passed=score>=(tq*0.7), pct=Math.round((score/tq)*100);')
lines.append('    if(!userProgress.quizScores) userProgress.quizScores={};')
lines.append('    if(!userProgress.quizScores[currentLevel]||score>userProgress.quizScores[currentLevel]){ userProgress.quizScores[currentLevel]=score; saveProgress(); }')
lines.append('    document.getElementById("results-score").textContent="Puntuacion: "+score+"/"+tq+" ("+pct+"%)";')
lines.append('    if(passed){')
lines.append('        document.getElementById("results-title").textContent="Felicidades!"; document.getElementById("results-title").style.color="var(--green)";')
lines.append('        document.getElementById("results-message").textContent="Has aprobado el cuestionario.";')
lines.append('        document.getElementById("results-icon").setAttribute("data-lucide","award"); document.getElementById("results-icon").style.color="var(--green)";')
lines.append('        document.getElementById("next-level-btn").classList.remove("hidden"); markLevelCompleted(currentLevel);')
lines.append('    } else {')
lines.append('        document.getElementById("results-title").textContent="Intentalo de nuevo!"; document.getElementById("results-title").style.color="var(--red)";')
lines.append('        document.getElementById("results-message").textContent="Necesitas al menos 70% para aprobar.";')
lines.append('        document.getElementById("results-icon").setAttribute("data-lucide","refresh-cw"); document.getElementById("results-icon").style.color="var(--red)";')
lines.append('        document.getElementById("next-level-btn").classList.add("hidden");')
lines.append('    }')
lines.append('    if(window.lucide) lucide.createIcons(); showPanel("results");')
lines.append('}')
lines.append('')
lines.append('document.getElementById("next-btn").addEventListener("click",()=>{ if(currentLessonStep<courseData[currentLevel].lesson.length-1){ currentLessonStep++; renderLesson(); } else startQuiz(); });')
lines.append('document.getElementById("prev-btn").addEventListener("click",()=>{ if(currentLessonStep>0){ currentLessonStep--; renderLesson(); } });')
lines.append('document.getElementById("close-lesson-btn").addEventListener("click",()=>{ renderLevelSelection(); showPanel("levelSelection"); });')
lines.append('document.getElementById("retry-lesson-btn").addEventListener("click",()=>startLevel(currentLevel));')
lines.append('document.getElementById("next-level-btn").addEventListener("click",()=>{ if(currentLevel+1<courseData.length) startLevel(currentLevel+1); else { renderLevelSelection(); showPanel("levelSelection"); } });')
lines.append('document.getElementById("theme-toggle").addEventListener("click",()=>{ const d=document.documentElement.classList.toggle("dark"); localStorage.setItem("theme",d?"dark":"light"); const ic=document.querySelector("#theme-toggle i"); ic.setAttribute("data-lucide",d?"sun":"moon"); if(window.lucide) lucide.createIcons(); });')
lines.append('</script>')
lines.append('<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/prism.js"></script>')
lines.append('<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-sql.min.js"></script>')
lines.append('<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/line-numbers/prism-line-numbers.min.js"></script>')
lines.append('</body>')
lines.append('</html>')

# Write the file WITHOUT courseData first
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"HTML+JS written: {os.path.getsize(OUT)} bytes")
print("SUCCESS - Now need to insert courseData before </script>")
